//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.20 at 01:32:56 AM CDT 
//


package org.rmt2.jaxb;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.RMT2Base;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}beanClassName"/>
 *         &lt;element ref="{}accountNo"/>
 *         &lt;element ref="{}active"/>
 *         &lt;element ref="{}addr1"/>
 *         &lt;element ref="{}addr2"/>
 *         &lt;element ref="{}addr3"/>
 *         &lt;element ref="{}addr4"/>
 *         &lt;element ref="{}addrBusinessId"/>
 *         &lt;element ref="{}addrId"/>
 *         &lt;element ref="{}addrPersonId"/>
 *         &lt;element ref="{}addrPhoneCell"/>
 *         &lt;element ref="{}addrPhoneExt"/>
 *         &lt;element ref="{}addrPhoneFax"/>
 *         &lt;element ref="{}addrPhoneHome"/>
 *         &lt;element ref="{}addrPhoneMain"/>
 *         &lt;element ref="{}addrPhonePager"/>
 *         &lt;element ref="{}addrPhoneWork"/>
 *         &lt;element ref="{}addrZip"/>
 *         &lt;element ref="{}addrZipext"/>
 *         &lt;element ref="{}balance"/>
 *         &lt;element ref="{}busType"/>
 *         &lt;element ref="{}businessId"/>
 *         &lt;element ref="{}contactEmail"/>
 *         &lt;element ref="{}contactExt"/>
 *         &lt;element ref="{}contactFirstname"/>
 *         &lt;element ref="{}contactLastname"/>
 *         &lt;element ref="{}contactPhone"/>
 *         &lt;element ref="{}creditLimit"/>
 *         &lt;element ref="{}customerId"/>
 *         &lt;element ref="{}dateCreated"/>
 *         &lt;element ref="{}dateUpdated"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}glAccountId"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}servType"/>
 *         &lt;element ref="{}shortname"/>
 *         &lt;element ref="{}taxId"/>
 *         &lt;element ref="{}userId"/>
 *         &lt;element ref="{}website"/>
 *         &lt;element ref="{}zipCity"/>
 *         &lt;element ref="{}zipState"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "beanClassName",
    "accountNo",
    "active",
    "addr1",
    "addr2",
    "addr3",
    "addr4",
    "addrBusinessId",
    "addrId",
    "addrPersonId",
    "addrPhoneCell",
    "addrPhoneExt",
    "addrPhoneFax",
    "addrPhoneHome",
    "addrPhoneMain",
    "addrPhonePager",
    "addrPhoneWork",
    "addrZip",
    "addrZipext",
    "balance",
    "busType",
    "businessId",
    "contactEmail",
    "contactExt",
    "contactFirstname",
    "contactLastname",
    "contactPhone",
    "creditLimit",
    "customerId",
    "dateCreated",
    "dateUpdated",
    "description",
    "glAccountId",
    "name",
    "servType",
    "shortname",
    "taxId",
    "userId",
    "website",
    "zipCity",
    "zipState"
})
@XmlRootElement(name = "CustomerData")
public class CustomerData
    extends RMT2Base
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String beanClassName;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String accountNo;
    @XmlElement(required = true)
    protected BigInteger active;
    @XmlElement(required = true)
    protected Addr1 addr1;
    @XmlElement(required = true)
    protected Addr2 addr2;
    @XmlElement(required = true)
    protected Addr3 addr3;
    @XmlElement(required = true)
    protected Addr4 addr4;
    @XmlElement(required = true)
    protected BigInteger addrBusinessId;
    @XmlElement(required = true)
    protected BigInteger addrId;
    @XmlElement(required = true)
    protected BigInteger addrPersonId;
    @XmlElement(required = true)
    protected AddrPhoneCell addrPhoneCell;
    @XmlElement(required = true)
    protected AddrPhoneExt addrPhoneExt;
    @XmlElement(required = true)
    protected AddrPhoneFax addrPhoneFax;
    @XmlElement(required = true)
    protected AddrPhoneHome addrPhoneHome;
    @XmlElement(required = true)
    protected AddrPhoneMain addrPhoneMain;
    @XmlElement(required = true)
    protected AddrPhonePager addrPhonePager;
    @XmlElement(required = true)
    protected AddrPhoneWork addrPhoneWork;
    @XmlElement(required = true)
    protected BigInteger addrZip;
    @XmlElement(required = true)
    protected BigInteger addrZipext;
    @XmlElement(required = true)
    protected BigDecimal balance;
    @XmlElement(required = true)
    protected BigInteger busType;
    @XmlElement(required = true)
    protected BigInteger businessId;
    @XmlElement(required = true)
    protected ContactEmail contactEmail;
    @XmlElement(required = true)
    protected ContactExt contactExt;
    @XmlElement(required = true)
    protected ContactFirstname contactFirstname;
    @XmlElement(required = true)
    protected ContactLastname contactLastname;
    @XmlElement(required = true)
    protected ContactPhone contactPhone;
    @XmlElement(required = true)
    protected BigDecimal creditLimit;
    @XmlElement(required = true)
    protected BigInteger customerId;
    @XmlElement(required = true)
    protected String dateCreated;
    @XmlElement(required = true)
    protected String dateUpdated;
    @XmlElement(required = true)
    protected Description description;
    @XmlElement(required = true)
    protected BigInteger glAccountId;
    @XmlElement(required = true)
    protected Name name;
    @XmlElement(required = true)
    protected BigInteger servType;
    @XmlElement(required = true)
    protected Shortname shortname;
    @XmlElement(required = true)
    protected TaxId taxId;
    @XmlElement(required = true)
    protected String userId;
    @XmlElement(required = true)
    protected Website website;
    @XmlElement(required = true)
    protected ZipCity zipCity;
    @XmlElement(required = true)
    protected ZipState zipState;

    /**
     * Gets the value of the beanClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeanClassName() {
        return beanClassName;
    }

    /**
     * Sets the value of the beanClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeanClassName(String value) {
        this.beanClassName = value;
    }

    /**
     * Gets the value of the accountNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * Sets the value of the accountNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNo(String value) {
        this.accountNo = value;
    }

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setActive(BigInteger value) {
        this.active = value;
    }

    /**
     * Gets the value of the addr1 property.
     * 
     * @return
     *     possible object is
     *     {@link Addr1 }
     *     
     */
    public Addr1 getAddr1() {
        return addr1;
    }

    /**
     * Sets the value of the addr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Addr1 }
     *     
     */
    public void setAddr1(Addr1 value) {
        this.addr1 = value;
    }

    /**
     * Gets the value of the addr2 property.
     * 
     * @return
     *     possible object is
     *     {@link Addr2 }
     *     
     */
    public Addr2 getAddr2() {
        return addr2;
    }

    /**
     * Sets the value of the addr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Addr2 }
     *     
     */
    public void setAddr2(Addr2 value) {
        this.addr2 = value;
    }

    /**
     * Gets the value of the addr3 property.
     * 
     * @return
     *     possible object is
     *     {@link Addr3 }
     *     
     */
    public Addr3 getAddr3() {
        return addr3;
    }

    /**
     * Sets the value of the addr3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Addr3 }
     *     
     */
    public void setAddr3(Addr3 value) {
        this.addr3 = value;
    }

    /**
     * Gets the value of the addr4 property.
     * 
     * @return
     *     possible object is
     *     {@link Addr4 }
     *     
     */
    public Addr4 getAddr4() {
        return addr4;
    }

    /**
     * Sets the value of the addr4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Addr4 }
     *     
     */
    public void setAddr4(Addr4 value) {
        this.addr4 = value;
    }

    /**
     * Gets the value of the addrBusinessId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAddrBusinessId() {
        return addrBusinessId;
    }

    /**
     * Sets the value of the addrBusinessId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAddrBusinessId(BigInteger value) {
        this.addrBusinessId = value;
    }

    /**
     * Gets the value of the addrId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAddrId() {
        return addrId;
    }

    /**
     * Sets the value of the addrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAddrId(BigInteger value) {
        this.addrId = value;
    }

    /**
     * Gets the value of the addrPersonId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAddrPersonId() {
        return addrPersonId;
    }

    /**
     * Sets the value of the addrPersonId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAddrPersonId(BigInteger value) {
        this.addrPersonId = value;
    }

    /**
     * Gets the value of the addrPhoneCell property.
     * 
     * @return
     *     possible object is
     *     {@link AddrPhoneCell }
     *     
     */
    public AddrPhoneCell getAddrPhoneCell() {
        return addrPhoneCell;
    }

    /**
     * Sets the value of the addrPhoneCell property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddrPhoneCell }
     *     
     */
    public void setAddrPhoneCell(AddrPhoneCell value) {
        this.addrPhoneCell = value;
    }

    /**
     * Gets the value of the addrPhoneExt property.
     * 
     * @return
     *     possible object is
     *     {@link AddrPhoneExt }
     *     
     */
    public AddrPhoneExt getAddrPhoneExt() {
        return addrPhoneExt;
    }

    /**
     * Sets the value of the addrPhoneExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddrPhoneExt }
     *     
     */
    public void setAddrPhoneExt(AddrPhoneExt value) {
        this.addrPhoneExt = value;
    }

    /**
     * Gets the value of the addrPhoneFax property.
     * 
     * @return
     *     possible object is
     *     {@link AddrPhoneFax }
     *     
     */
    public AddrPhoneFax getAddrPhoneFax() {
        return addrPhoneFax;
    }

    /**
     * Sets the value of the addrPhoneFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddrPhoneFax }
     *     
     */
    public void setAddrPhoneFax(AddrPhoneFax value) {
        this.addrPhoneFax = value;
    }

    /**
     * Gets the value of the addrPhoneHome property.
     * 
     * @return
     *     possible object is
     *     {@link AddrPhoneHome }
     *     
     */
    public AddrPhoneHome getAddrPhoneHome() {
        return addrPhoneHome;
    }

    /**
     * Sets the value of the addrPhoneHome property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddrPhoneHome }
     *     
     */
    public void setAddrPhoneHome(AddrPhoneHome value) {
        this.addrPhoneHome = value;
    }

    /**
     * Gets the value of the addrPhoneMain property.
     * 
     * @return
     *     possible object is
     *     {@link AddrPhoneMain }
     *     
     */
    public AddrPhoneMain getAddrPhoneMain() {
        return addrPhoneMain;
    }

    /**
     * Sets the value of the addrPhoneMain property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddrPhoneMain }
     *     
     */
    public void setAddrPhoneMain(AddrPhoneMain value) {
        this.addrPhoneMain = value;
    }

    /**
     * Gets the value of the addrPhonePager property.
     * 
     * @return
     *     possible object is
     *     {@link AddrPhonePager }
     *     
     */
    public AddrPhonePager getAddrPhonePager() {
        return addrPhonePager;
    }

    /**
     * Sets the value of the addrPhonePager property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddrPhonePager }
     *     
     */
    public void setAddrPhonePager(AddrPhonePager value) {
        this.addrPhonePager = value;
    }

    /**
     * Gets the value of the addrPhoneWork property.
     * 
     * @return
     *     possible object is
     *     {@link AddrPhoneWork }
     *     
     */
    public AddrPhoneWork getAddrPhoneWork() {
        return addrPhoneWork;
    }

    /**
     * Sets the value of the addrPhoneWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddrPhoneWork }
     *     
     */
    public void setAddrPhoneWork(AddrPhoneWork value) {
        this.addrPhoneWork = value;
    }

    /**
     * Gets the value of the addrZip property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAddrZip() {
        return addrZip;
    }

    /**
     * Sets the value of the addrZip property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAddrZip(BigInteger value) {
        this.addrZip = value;
    }

    /**
     * Gets the value of the addrZipext property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAddrZipext() {
        return addrZipext;
    }

    /**
     * Sets the value of the addrZipext property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAddrZipext(BigInteger value) {
        this.addrZipext = value;
    }

    /**
     * Gets the value of the balance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * Sets the value of the balance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBalance(BigDecimal value) {
        this.balance = value;
    }

    /**
     * Gets the value of the busType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBusType() {
        return busType;
    }

    /**
     * Sets the value of the busType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBusType(BigInteger value) {
        this.busType = value;
    }

    /**
     * Gets the value of the businessId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBusinessId() {
        return businessId;
    }

    /**
     * Sets the value of the businessId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBusinessId(BigInteger value) {
        this.businessId = value;
    }

    /**
     * Gets the value of the contactEmail property.
     * 
     * @return
     *     possible object is
     *     {@link ContactEmail }
     *     
     */
    public ContactEmail getContactEmail() {
        return contactEmail;
    }

    /**
     * Sets the value of the contactEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactEmail }
     *     
     */
    public void setContactEmail(ContactEmail value) {
        this.contactEmail = value;
    }

    /**
     * Gets the value of the contactExt property.
     * 
     * @return
     *     possible object is
     *     {@link ContactExt }
     *     
     */
    public ContactExt getContactExt() {
        return contactExt;
    }

    /**
     * Sets the value of the contactExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactExt }
     *     
     */
    public void setContactExt(ContactExt value) {
        this.contactExt = value;
    }

    /**
     * Gets the value of the contactFirstname property.
     * 
     * @return
     *     possible object is
     *     {@link ContactFirstname }
     *     
     */
    public ContactFirstname getContactFirstname() {
        return contactFirstname;
    }

    /**
     * Sets the value of the contactFirstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactFirstname }
     *     
     */
    public void setContactFirstname(ContactFirstname value) {
        this.contactFirstname = value;
    }

    /**
     * Gets the value of the contactLastname property.
     * 
     * @return
     *     possible object is
     *     {@link ContactLastname }
     *     
     */
    public ContactLastname getContactLastname() {
        return contactLastname;
    }

    /**
     * Sets the value of the contactLastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactLastname }
     *     
     */
    public void setContactLastname(ContactLastname value) {
        this.contactLastname = value;
    }

    /**
     * Gets the value of the contactPhone property.
     * 
     * @return
     *     possible object is
     *     {@link ContactPhone }
     *     
     */
    public ContactPhone getContactPhone() {
        return contactPhone;
    }

    /**
     * Sets the value of the contactPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactPhone }
     *     
     */
    public void setContactPhone(ContactPhone value) {
        this.contactPhone = value;
    }

    /**
     * Gets the value of the creditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCreditLimit() {
        return creditLimit;
    }

    /**
     * Sets the value of the creditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCreditLimit(BigDecimal value) {
        this.creditLimit = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCustomerId(BigInteger value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the dateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateCreated() {
        return dateCreated;
    }

    /**
     * Sets the value of the dateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateCreated(String value) {
        this.dateCreated = value;
    }

    /**
     * Gets the value of the dateUpdated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateUpdated() {
        return dateUpdated;
    }

    /**
     * Sets the value of the dateUpdated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateUpdated(String value) {
        this.dateUpdated = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the glAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGlAccountId() {
        return glAccountId;
    }

    /**
     * Sets the value of the glAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGlAccountId(BigInteger value) {
        this.glAccountId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the servType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getServType() {
        return servType;
    }

    /**
     * Sets the value of the servType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setServType(BigInteger value) {
        this.servType = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link Shortname }
     *     
     */
    public Shortname getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shortname }
     *     
     */
    public void setShortname(Shortname value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the taxId property.
     * 
     * @return
     *     possible object is
     *     {@link TaxId }
     *     
     */
    public TaxId getTaxId() {
        return taxId;
    }

    /**
     * Sets the value of the taxId property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxId }
     *     
     */
    public void setTaxId(TaxId value) {
        this.taxId = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the website property.
     * 
     * @return
     *     possible object is
     *     {@link Website }
     *     
     */
    public Website getWebsite() {
        return website;
    }

    /**
     * Sets the value of the website property.
     * 
     * @param value
     *     allowed object is
     *     {@link Website }
     *     
     */
    public void setWebsite(Website value) {
        this.website = value;
    }

    /**
     * Gets the value of the zipCity property.
     * 
     * @return
     *     possible object is
     *     {@link ZipCity }
     *     
     */
    public ZipCity getZipCity() {
        return zipCity;
    }

    /**
     * Sets the value of the zipCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZipCity }
     *     
     */
    public void setZipCity(ZipCity value) {
        this.zipCity = value;
    }

    /**
     * Gets the value of the zipState property.
     * 
     * @return
     *     possible object is
     *     {@link ZipState }
     *     
     */
    public ZipState getZipState() {
        return zipState;
    }

    /**
     * Sets the value of the zipState property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZipState }
     *     
     */
    public void setZipState(ZipState value) {
        this.zipState = value;
    }

}
