//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.23 at 03:57:07 PM CDT 
//


package org.rmt2.jaxb;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.RMT2Base;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="appRoot" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pageTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="accountNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addr1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addr2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addr3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addr4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addrPhoneCell" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addrPhoneExt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addrPhoneFax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addrPhoneHome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addrPhoneMain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addrPhonePager" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addrPhoneWork" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="addrZip" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="addrZipext" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="businessId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="contactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="contactExt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="contactFirstname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="contactLastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="contactPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="creditLimit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="glAccountId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="taxId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="zipCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="zipState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SalesOrderData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="invoiced" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="orderTotal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="soId" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="XactData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="beanClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="bankTransInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="confirmNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="documentId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="entityRefNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="postedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tenderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="xactAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="xactDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="xactId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="xactTypeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "appRoot",
    "pageTitle",
    "customerData",
    "salesOrderData",
    "xactData"
})
@XmlRootElement(name = "CustomerPaymentConfirmation")
public class CustomerPaymentConfirmation
    extends RMT2Base
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String appRoot;
    @XmlElement(required = true)
    protected String pageTitle;
    @XmlElement(name = "CustomerData", required = true)
    protected CustomerPaymentConfirmation.CustomerData customerData;
    @XmlElement(name = "SalesOrderData", required = true)
    protected CustomerPaymentConfirmation.SalesOrderData salesOrderData;
    @XmlElement(name = "XactData", required = true)
    protected CustomerPaymentConfirmation.XactData xactData;

    /**
     * Gets the value of the appRoot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppRoot() {
        return appRoot;
    }

    /**
     * Sets the value of the appRoot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppRoot(String value) {
        this.appRoot = value;
    }

    /**
     * Gets the value of the pageTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageTitle() {
        return pageTitle;
    }

    /**
     * Sets the value of the pageTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageTitle(String value) {
        this.pageTitle = value;
    }

    /**
     * Gets the value of the customerData property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerPaymentConfirmation.CustomerData }
     *     
     */
    public CustomerPaymentConfirmation.CustomerData getCustomerData() {
        return customerData;
    }

    /**
     * Sets the value of the customerData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerPaymentConfirmation.CustomerData }
     *     
     */
    public void setCustomerData(CustomerPaymentConfirmation.CustomerData value) {
        this.customerData = value;
    }

    /**
     * Gets the value of the salesOrderData property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerPaymentConfirmation.SalesOrderData }
     *     
     */
    public CustomerPaymentConfirmation.SalesOrderData getSalesOrderData() {
        return salesOrderData;
    }

    /**
     * Sets the value of the salesOrderData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerPaymentConfirmation.SalesOrderData }
     *     
     */
    public void setSalesOrderData(CustomerPaymentConfirmation.SalesOrderData value) {
        this.salesOrderData = value;
    }

    /**
     * Gets the value of the xactData property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerPaymentConfirmation.XactData }
     *     
     */
    public CustomerPaymentConfirmation.XactData getXactData() {
        return xactData;
    }

    /**
     * Sets the value of the xactData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerPaymentConfirmation.XactData }
     *     
     */
    public void setXactData(CustomerPaymentConfirmation.XactData value) {
        this.xactData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="accountNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addr1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addr2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addr3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addr4" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addrPhoneCell" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addrPhoneExt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addrPhoneFax" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addrPhoneHome" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addrPhoneMain" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addrPhonePager" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addrPhoneWork" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="addrZip" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="addrZipext" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="businessId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="contactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="contactExt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="contactFirstname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="contactLastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="contactPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="creditLimit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="glAccountId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="taxId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="zipCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="zipState" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accountNo",
        "addr1",
        "addr2",
        "addr3",
        "addr4",
        "addrPhoneCell",
        "addrPhoneExt",
        "addrPhoneFax",
        "addrPhoneHome",
        "addrPhoneMain",
        "addrPhonePager",
        "addrPhoneWork",
        "addrZip",
        "addrZipext",
        "balance",
        "businessId",
        "contactEmail",
        "contactExt",
        "contactFirstname",
        "contactLastname",
        "contactPhone",
        "creditLimit",
        "customerId",
        "description",
        "glAccountId",
        "name",
        "taxId",
        "zipCity",
        "zipState"
    })
    public static class CustomerData
        extends RMT2Base
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected String accountNo;
        @XmlElement(required = true)
        protected String addr1;
        @XmlElement(required = true)
        protected String addr2;
        @XmlElement(required = true)
        protected String addr3;
        @XmlElement(required = true)
        protected String addr4;
        @XmlElement(required = true)
        protected String addrPhoneCell;
        @XmlElement(required = true)
        protected String addrPhoneExt;
        @XmlElement(required = true)
        protected String addrPhoneFax;
        @XmlElement(required = true)
        protected String addrPhoneHome;
        @XmlElement(required = true)
        protected String addrPhoneMain;
        @XmlElement(required = true)
        protected String addrPhonePager;
        @XmlElement(required = true)
        protected String addrPhoneWork;
        @XmlSchemaType(name = "unsignedByte")
        protected short addrZip;
        @XmlSchemaType(name = "unsignedByte")
        protected short addrZipext;
        @XmlElement(required = true)
        protected BigDecimal balance;
        @XmlElement(required = true)
        protected BigInteger businessId;
        @XmlElement(required = true)
        protected String contactEmail;
        @XmlElement(required = true)
        protected String contactExt;
        @XmlElement(required = true)
        protected String contactFirstname;
        @XmlElement(required = true)
        protected String contactLastname;
        @XmlElement(required = true)
        protected String contactPhone;
        @XmlElement(required = true)
        protected BigDecimal creditLimit;
        @XmlElement(required = true)
        protected BigInteger customerId;
        @XmlElement(required = true)
        protected String description;
        @XmlElement(required = true)
        protected BigInteger glAccountId;
        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String taxId;
        @XmlElement(required = true)
        protected String zipCity;
        @XmlElement(required = true)
        protected String zipState;

        /**
         * Gets the value of the accountNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccountNo() {
            return accountNo;
        }

        /**
         * Sets the value of the accountNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccountNo(String value) {
            this.accountNo = value;
        }

        /**
         * Gets the value of the addr1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddr1() {
            return addr1;
        }

        /**
         * Sets the value of the addr1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddr1(String value) {
            this.addr1 = value;
        }

        /**
         * Gets the value of the addr2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddr2() {
            return addr2;
        }

        /**
         * Sets the value of the addr2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddr2(String value) {
            this.addr2 = value;
        }

        /**
         * Gets the value of the addr3 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddr3() {
            return addr3;
        }

        /**
         * Sets the value of the addr3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddr3(String value) {
            this.addr3 = value;
        }

        /**
         * Gets the value of the addr4 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddr4() {
            return addr4;
        }

        /**
         * Sets the value of the addr4 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddr4(String value) {
            this.addr4 = value;
        }

        /**
         * Gets the value of the addrPhoneCell property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddrPhoneCell() {
            return addrPhoneCell;
        }

        /**
         * Sets the value of the addrPhoneCell property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddrPhoneCell(String value) {
            this.addrPhoneCell = value;
        }

        /**
         * Gets the value of the addrPhoneExt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddrPhoneExt() {
            return addrPhoneExt;
        }

        /**
         * Sets the value of the addrPhoneExt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddrPhoneExt(String value) {
            this.addrPhoneExt = value;
        }

        /**
         * Gets the value of the addrPhoneFax property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddrPhoneFax() {
            return addrPhoneFax;
        }

        /**
         * Sets the value of the addrPhoneFax property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddrPhoneFax(String value) {
            this.addrPhoneFax = value;
        }

        /**
         * Gets the value of the addrPhoneHome property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddrPhoneHome() {
            return addrPhoneHome;
        }

        /**
         * Sets the value of the addrPhoneHome property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddrPhoneHome(String value) {
            this.addrPhoneHome = value;
        }

        /**
         * Gets the value of the addrPhoneMain property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddrPhoneMain() {
            return addrPhoneMain;
        }

        /**
         * Sets the value of the addrPhoneMain property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddrPhoneMain(String value) {
            this.addrPhoneMain = value;
        }

        /**
         * Gets the value of the addrPhonePager property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddrPhonePager() {
            return addrPhonePager;
        }

        /**
         * Sets the value of the addrPhonePager property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddrPhonePager(String value) {
            this.addrPhonePager = value;
        }

        /**
         * Gets the value of the addrPhoneWork property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddrPhoneWork() {
            return addrPhoneWork;
        }

        /**
         * Sets the value of the addrPhoneWork property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddrPhoneWork(String value) {
            this.addrPhoneWork = value;
        }

        /**
         * Gets the value of the addrZip property.
         * 
         */
        public short getAddrZip() {
            return addrZip;
        }

        /**
         * Sets the value of the addrZip property.
         * 
         */
        public void setAddrZip(short value) {
            this.addrZip = value;
        }

        /**
         * Gets the value of the addrZipext property.
         * 
         */
        public short getAddrZipext() {
            return addrZipext;
        }

        /**
         * Sets the value of the addrZipext property.
         * 
         */
        public void setAddrZipext(short value) {
            this.addrZipext = value;
        }

        /**
         * Gets the value of the balance property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getBalance() {
            return balance;
        }

        /**
         * Sets the value of the balance property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setBalance(BigDecimal value) {
            this.balance = value;
        }

        /**
         * Gets the value of the businessId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getBusinessId() {
            return businessId;
        }

        /**
         * Sets the value of the businessId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setBusinessId(BigInteger value) {
            this.businessId = value;
        }

        /**
         * Gets the value of the contactEmail property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactEmail() {
            return contactEmail;
        }

        /**
         * Sets the value of the contactEmail property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactEmail(String value) {
            this.contactEmail = value;
        }

        /**
         * Gets the value of the contactExt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactExt() {
            return contactExt;
        }

        /**
         * Sets the value of the contactExt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactExt(String value) {
            this.contactExt = value;
        }

        /**
         * Gets the value of the contactFirstname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactFirstname() {
            return contactFirstname;
        }

        /**
         * Sets the value of the contactFirstname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactFirstname(String value) {
            this.contactFirstname = value;
        }

        /**
         * Gets the value of the contactLastname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactLastname() {
            return contactLastname;
        }

        /**
         * Sets the value of the contactLastname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactLastname(String value) {
            this.contactLastname = value;
        }

        /**
         * Gets the value of the contactPhone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactPhone() {
            return contactPhone;
        }

        /**
         * Sets the value of the contactPhone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactPhone(String value) {
            this.contactPhone = value;
        }

        /**
         * Gets the value of the creditLimit property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getCreditLimit() {
            return creditLimit;
        }

        /**
         * Sets the value of the creditLimit property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setCreditLimit(BigDecimal value) {
            this.creditLimit = value;
        }

        /**
         * Gets the value of the customerId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCustomerId() {
            return customerId;
        }

        /**
         * Sets the value of the customerId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCustomerId(BigInteger value) {
            this.customerId = value;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the glAccountId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getGlAccountId() {
            return glAccountId;
        }

        /**
         * Sets the value of the glAccountId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setGlAccountId(BigInteger value) {
            this.glAccountId = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the taxId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTaxId() {
            return taxId;
        }

        /**
         * Sets the value of the taxId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTaxId(String value) {
            this.taxId = value;
        }

        /**
         * Gets the value of the zipCity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZipCity() {
            return zipCity;
        }

        /**
         * Sets the value of the zipCity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZipCity(String value) {
            this.zipCity = value;
        }

        /**
         * Gets the value of the zipState property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZipState() {
            return zipState;
        }

        /**
         * Sets the value of the zipState property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZipState(String value) {
            this.zipState = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="effectiveDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="invoiced" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="orderTotal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="soId" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "customerId",
        "effectiveDate",
        "invoiced",
        "orderTotal",
        "soId"
    })
    public static class SalesOrderData
        extends RMT2Base
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected BigInteger customerId;
        @XmlElement(required = true)
        protected String effectiveDate;
        @XmlElement(required = true)
        protected BigInteger invoiced;
        @XmlElement(required = true)
        protected BigDecimal orderTotal;
        @XmlSchemaType(name = "unsignedShort")
        protected int soId;

        /**
         * Gets the value of the customerId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCustomerId() {
            return customerId;
        }

        /**
         * Sets the value of the customerId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCustomerId(BigInteger value) {
            this.customerId = value;
        }

        /**
         * Gets the value of the effectiveDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEffectiveDate() {
            return effectiveDate;
        }

        /**
         * Sets the value of the effectiveDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEffectiveDate(String value) {
            this.effectiveDate = value;
        }

        /**
         * Gets the value of the invoiced property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getInvoiced() {
            return invoiced;
        }

        /**
         * Sets the value of the invoiced property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setInvoiced(BigInteger value) {
            this.invoiced = value;
        }

        /**
         * Gets the value of the orderTotal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getOrderTotal() {
            return orderTotal;
        }

        /**
         * Sets the value of the orderTotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setOrderTotal(BigDecimal value) {
            this.orderTotal = value;
        }

        /**
         * Gets the value of the soId property.
         * 
         */
        public int getSoId() {
            return soId;
        }

        /**
         * Sets the value of the soId property.
         * 
         */
        public void setSoId(int value) {
            this.soId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="beanClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="bankTransInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="confirmNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="documentId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="entityRefNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="postedDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="reason" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tenderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="xactAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="xactDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="xactId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="xactTypeId" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "beanClassName",
        "bankTransInd",
        "confirmNo",
        "documentId",
        "entityRefNo",
        "postedDate",
        "reason",
        "tenderId",
        "xactAmount",
        "xactDate",
        "xactId",
        "xactTypeId"
    })
    public static class XactData
        extends RMT2Base
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected String beanClassName;
        @XmlElement(required = true)
        protected String bankTransInd;
        @XmlElement(required = true)
        protected String confirmNo;
        @XmlElement(required = true)
        protected BigInteger documentId;
        @XmlElement(required = true)
        protected String entityRefNo;
        @XmlElement(required = true)
        protected String postedDate;
        @XmlElement(required = true)
        protected String reason;
        @XmlElement(required = true)
        protected String tenderId;
        @XmlElement(required = true)
        protected BigDecimal xactAmount;
        @XmlElement(required = true)
        protected String xactDate;
        @XmlElement(required = true)
        protected BigInteger xactId;
        @XmlElement(required = true)
        protected BigInteger xactTypeId;

        /**
         * Gets the value of the beanClassName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBeanClassName() {
            return beanClassName;
        }

        /**
         * Sets the value of the beanClassName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBeanClassName(String value) {
            this.beanClassName = value;
        }

        /**
         * Gets the value of the bankTransInd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBankTransInd() {
            return bankTransInd;
        }

        /**
         * Sets the value of the bankTransInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBankTransInd(String value) {
            this.bankTransInd = value;
        }

        /**
         * Gets the value of the confirmNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConfirmNo() {
            return confirmNo;
        }

        /**
         * Sets the value of the confirmNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConfirmNo(String value) {
            this.confirmNo = value;
        }

        /**
         * Gets the value of the documentId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getDocumentId() {
            return documentId;
        }

        /**
         * Sets the value of the documentId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDocumentId(BigInteger value) {
            this.documentId = value;
        }

        /**
         * Gets the value of the entityRefNo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEntityRefNo() {
            return entityRefNo;
        }

        /**
         * Sets the value of the entityRefNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEntityRefNo(String value) {
            this.entityRefNo = value;
        }

        /**
         * Gets the value of the postedDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPostedDate() {
            return postedDate;
        }

        /**
         * Sets the value of the postedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPostedDate(String value) {
            this.postedDate = value;
        }

        /**
         * Gets the value of the reason property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReason() {
            return reason;
        }

        /**
         * Sets the value of the reason property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReason(String value) {
            this.reason = value;
        }

        /**
         * Gets the value of the tenderId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTenderId() {
            return tenderId;
        }

        /**
         * Sets the value of the tenderId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTenderId(String value) {
            this.tenderId = value;
        }

        /**
         * Gets the value of the xactAmount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getXactAmount() {
            return xactAmount;
        }

        /**
         * Sets the value of the xactAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setXactAmount(BigDecimal value) {
            this.xactAmount = value;
        }

        /**
         * Gets the value of the xactDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXactDate() {
            return xactDate;
        }

        /**
         * Sets the value of the xactDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXactDate(String value) {
            this.xactDate = value;
        }

        /**
         * Gets the value of the xactId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getXactId() {
            return xactId;
        }

        /**
         * Sets the value of the xactId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setXactId(BigInteger value) {
            this.xactId = value;
        }

        /**
         * Gets the value of the xactTypeId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getXactTypeId() {
            return xactTypeId;
        }

        /**
         * Sets the value of the xactTypeId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setXactTypeId(BigInteger value) {
            this.xactTypeId = value;
        }

    }

}
