//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.20 at 01:32:56 AM CDT 
//


package org.rmt2.jaxb;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.rmt2.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OrderByAvailable_QNAME = new QName("", "orderByAvailable");
    private final static QName _Reason_QNAME = new QName("", "reason");
    private final static QName _BeanClassName_QNAME = new QName("", "beanClassName");
    private final static QName _SerializeXml_QNAME = new QName("", "serializeXml");
    private final static QName _XactSubtypeId_QNAME = new QName("", "xactSubtypeId");
    private final static QName _GlAccountId_QNAME = new QName("", "glAccountId");
    private final static QName _BusinessId_QNAME = new QName("", "businessId");
    private final static QName _ResultsetType_QNAME = new QName("", "resultsetType");
    private final static QName _TenderId_QNAME = new QName("", "tenderId");
    private final static QName _DateCreated_QNAME = new QName("", "dateCreated");
    private final static QName _XactDate_QNAME = new QName("", "xactDate");
    private final static QName _Balance_QNAME = new QName("", "balance");
    private final static QName _AccountNo_QNAME = new QName("", "accountNo");
    private final static QName _CustomerId_QNAME = new QName("", "customerId");
    private final static QName _XactTypeId_QNAME = new QName("", "xactTypeId");
    private final static QName _CreditLimit_QNAME = new QName("", "creditLimit");
    private final static QName _DataSourceClassName_QNAME = new QName("", "dataSourceClassName");
    private final static QName _AddrId_QNAME = new QName("", "addrId");
    private final static QName _ServType_QNAME = new QName("", "servType");
    private final static QName _BusType_QNAME = new QName("", "busType");
    private final static QName _DataSourcePackage_QNAME = new QName("", "dataSourcePackage");
    private final static QName _XactId_QNAME = new QName("", "xactId");
    private final static QName _SoId_QNAME = new QName("", "soId");
    private final static QName _InClauseAvailable_QNAME = new QName("", "inClauseAvailable");
    private final static QName _Invoiced_QNAME = new QName("", "invoiced");
    private final static QName _CustomCriteriaAvailable_QNAME = new QName("", "customCriteriaAvailable");
    private final static QName _DataSourceRoot_QNAME = new QName("", "dataSourceRoot");
    private final static QName _AddrZip_QNAME = new QName("", "addrZip");
    private final static QName _Active_QNAME = new QName("", "active");
    private final static QName _AddrZipext_QNAME = new QName("", "addrZipext");
    private final static QName _UserId_QNAME = new QName("", "userId");
    private final static QName _DataSourceName_QNAME = new QName("", "dataSourceName");
    private final static QName _OrderTotal_QNAME = new QName("", "orderTotal");
    private final static QName _CriteriaAvailable_QNAME = new QName("", "criteriaAvailable");
    private final static QName _DateUpdated_QNAME = new QName("", "dateUpdated");
    private final static QName _AddrPersonId_QNAME = new QName("", "addrPersonId");
    private final static QName _XactAmount_QNAME = new QName("", "xactAmount");
    private final static QName _AddrBusinessId_QNAME = new QName("", "addrBusinessId");
    private final static QName _DocumentId_QNAME = new QName("", "documentId");
    private final static QName _EffectiveDate_QNAME = new QName("", "effectiveDate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.rmt2.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PostalRequest }
     * 
     */
    public PostalRequest createPostalRequest() {
        return new PostalRequest();
    }

    /**
     * Create an instance of {@link FileName }
     * 
     */
    public FileName createFileName() {
        return new FileName();
    }

    /**
     * Create an instance of {@link ZipCity }
     * 
     */
    public ZipCity createZipCity() {
        return new ZipCity();
    }

    /**
     * Create an instance of {@link XactData }
     * 
     */
    public XactData createXactData() {
        return new XactData();
    }

    /**
     * Create an instance of {@link BankTransInd }
     * 
     */
    public BankTransInd createBankTransInd() {
        return new BankTransInd();
    }

    /**
     * Create an instance of {@link ConfirmNo }
     * 
     */
    public ConfirmNo createConfirmNo() {
        return new ConfirmNo();
    }

    /**
     * Create an instance of {@link EntityRefNo }
     * 
     */
    public EntityRefNo createEntityRefNo() {
        return new EntityRefNo();
    }

    /**
     * Create an instance of {@link IpCreated }
     * 
     */
    public IpCreated createIpCreated() {
        return new IpCreated();
    }

    /**
     * Create an instance of {@link IpUpdated }
     * 
     */
    public IpUpdated createIpUpdated() {
        return new IpUpdated();
    }

    /**
     * Create an instance of {@link NegInstrNo }
     * 
     */
    public NegInstrNo createNegInstrNo() {
        return new NegInstrNo();
    }

    /**
     * Create an instance of {@link Null }
     * 
     */
    public Null createNull() {
        return new Null();
    }

    /**
     * Create an instance of {@link PostedDate }
     * 
     */
    public PostedDate createPostedDate() {
        return new PostedDate();
    }

    /**
     * Create an instance of {@link RowLimitClause }
     * 
     */
    public RowLimitClause createRowLimitClause() {
        return new RowLimitClause();
    }

    /**
     * Create an instance of {@link ProvinceRequest }
     * 
     */
    public ProvinceRequest createProvinceRequest() {
        return new ProvinceRequest();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public HeaderType createHeaderType() {
        return new HeaderType();
    }

    /**
     * Create an instance of {@link OrderByType }
     * 
     */
    public OrderByType createOrderByType() {
        return new OrderByType();
    }

    /**
     * Create an instance of {@link UserAuthenticationRequest }
     * 
     */
    public UserAuthenticationRequest createUserAuthenticationRequest() {
        return new UserAuthenticationRequest();
    }

    /**
     * Create an instance of {@link UserLoginType }
     * 
     */
    public UserLoginType createUserLoginType() {
        return new UserLoginType();
    }

    /**
     * Create an instance of {@link Shortname }
     * 
     */
    public Shortname createShortname() {
        return new Shortname();
    }

    /**
     * Create an instance of {@link ProvinceResponse }
     * 
     */
    public ProvinceResponse createProvinceResponse() {
        return new ProvinceResponse();
    }

    /**
     * Create an instance of {@link ReplyStatusType }
     * 
     */
    public ReplyStatusType createReplyStatusType() {
        return new ReplyStatusType();
    }

    /**
     * Create an instance of {@link StateType }
     * 
     */
    public StateType createStateType() {
        return new StateType();
    }

    /**
     * Create an instance of {@link SalesOrderData }
     * 
     */
    public SalesOrderData createSalesOrderData() {
        return new SalesOrderData();
    }

    /**
     * Create an instance of {@link ContactFirstname }
     * 
     */
    public ContactFirstname createContactFirstname() {
        return new ContactFirstname();
    }

    /**
     * Create an instance of {@link ZipState }
     * 
     */
    public ZipState createZipState() {
        return new ZipState();
    }

    /**
     * Create an instance of {@link PostalRequest.PostalCriteria }
     * 
     */
    public PostalRequest.PostalCriteria createPostalRequestPostalCriteria() {
        return new PostalRequest.PostalCriteria();
    }

    /**
     * Create an instance of {@link AddrPhoneHome }
     * 
     */
    public AddrPhoneHome createAddrPhoneHome() {
        return new AddrPhoneHome();
    }

    /**
     * Create an instance of {@link Website }
     * 
     */
    public Website createWebsite() {
        return new Website();
    }

    /**
     * Create an instance of {@link AuthenticationAppResourcesResponse }
     * 
     */
    public AuthenticationAppResourcesResponse createAuthenticationAppResourcesResponse() {
        return new AuthenticationAppResourcesResponse();
    }

    /**
     * Create an instance of {@link AuthDetailGroup }
     * 
     */
    public AuthDetailGroup createAuthDetailGroup() {
        return new AuthDetailGroup();
    }

    /**
     * Create an instance of {@link AuthenticationAppResourcesRequest }
     * 
     */
    public AuthenticationAppResourcesRequest createAuthenticationAppResourcesRequest() {
        return new AuthenticationAppResourcesRequest();
    }

    /**
     * Create an instance of {@link AuthCriteriaGroup }
     * 
     */
    public AuthCriteriaGroup createAuthCriteriaGroup() {
        return new AuthCriteriaGroup();
    }

    /**
     * Create an instance of {@link AddrPhonePager }
     * 
     */
    public AddrPhonePager createAddrPhonePager() {
        return new AddrPhonePager();
    }

    /**
     * Create an instance of {@link AddrPhoneMain }
     * 
     */
    public AddrPhoneMain createAddrPhoneMain() {
        return new AddrPhoneMain();
    }

    /**
     * Create an instance of {@link ContactPhone }
     * 
     */
    public ContactPhone createContactPhone() {
        return new ContactPhone();
    }

    /**
     * Create an instance of {@link UserAuthenticationResponse }
     * 
     */
    public UserAuthenticationResponse createUserAuthenticationResponse() {
        return new UserAuthenticationResponse();
    }

    /**
     * Create an instance of {@link UserSessionType }
     * 
     */
    public UserSessionType createUserSessionType() {
        return new UserSessionType();
    }

    /**
     * Create an instance of {@link MultimediaResponse }
     * 
     */
    public MultimediaResponse createMultimediaResponse() {
        return new MultimediaResponse();
    }

    /**
     * Create an instance of {@link MimeContentType }
     * 
     */
    public MimeContentType createMimeContentType() {
        return new MimeContentType();
    }

    /**
     * Create an instance of {@link AddrPhoneWork }
     * 
     */
    public AddrPhoneWork createAddrPhoneWork() {
        return new AddrPhoneWork();
    }

    /**
     * Create an instance of {@link PostalResponse }
     * 
     */
    public PostalResponse createPostalResponse() {
        return new PostalResponse();
    }

    /**
     * Create an instance of {@link ZipcodeType }
     * 
     */
    public ZipcodeType createZipcodeType() {
        return new ZipcodeType();
    }

    /**
     * Create an instance of {@link ZipcodeFullType }
     * 
     */
    public ZipcodeFullType createZipcodeFullType() {
        return new ZipcodeFullType();
    }

    /**
     * Create an instance of {@link CountryType }
     * 
     */
    public CountryType createCountryType() {
        return new CountryType();
    }

    /**
     * Create an instance of {@link IpDetails }
     * 
     */
    public IpDetails createIpDetails() {
        return new IpDetails();
    }

    /**
     * Create an instance of {@link TimezoneType }
     * 
     */
    public TimezoneType createTimezoneType() {
        return new TimezoneType();
    }

    /**
     * Create an instance of {@link PaginationType }
     * 
     */
    public PaginationType createPaginationType() {
        return new PaginationType();
    }

    /**
     * Create an instance of {@link AccountingTransactionResponse }
     * 
     */
    public AccountingTransactionResponse createAccountingTransactionResponse() {
        return new AccountingTransactionResponse();
    }

    /**
     * Create an instance of {@link TransactionDetailGroup }
     * 
     */
    public TransactionDetailGroup createTransactionDetailGroup() {
        return new TransactionDetailGroup();
    }

    /**
     * Create an instance of {@link CustomerPaymentConfirmation }
     * 
     */
    public CustomerPaymentConfirmation createCustomerPaymentConfirmation() {
        return new CustomerPaymentConfirmation();
    }

    /**
     * Create an instance of {@link CustomerData }
     * 
     */
    public CustomerData createCustomerData() {
        return new CustomerData();
    }

    /**
     * Create an instance of {@link Addr1 }
     * 
     */
    public Addr1 createAddr1() {
        return new Addr1();
    }

    /**
     * Create an instance of {@link Addr2 }
     * 
     */
    public Addr2 createAddr2() {
        return new Addr2();
    }

    /**
     * Create an instance of {@link Addr3 }
     * 
     */
    public Addr3 createAddr3() {
        return new Addr3();
    }

    /**
     * Create an instance of {@link Addr4 }
     * 
     */
    public Addr4 createAddr4() {
        return new Addr4();
    }

    /**
     * Create an instance of {@link AddrPhoneCell }
     * 
     */
    public AddrPhoneCell createAddrPhoneCell() {
        return new AddrPhoneCell();
    }

    /**
     * Create an instance of {@link AddrPhoneExt }
     * 
     */
    public AddrPhoneExt createAddrPhoneExt() {
        return new AddrPhoneExt();
    }

    /**
     * Create an instance of {@link AddrPhoneFax }
     * 
     */
    public AddrPhoneFax createAddrPhoneFax() {
        return new AddrPhoneFax();
    }

    /**
     * Create an instance of {@link ContactEmail }
     * 
     */
    public ContactEmail createContactEmail() {
        return new ContactEmail();
    }

    /**
     * Create an instance of {@link ContactExt }
     * 
     */
    public ContactExt createContactExt() {
        return new ContactExt();
    }

    /**
     * Create an instance of {@link ContactLastname }
     * 
     */
    public ContactLastname createContactLastname() {
        return new ContactLastname();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link TaxId }
     * 
     */
    public TaxId createTaxId() {
        return new TaxId();
    }

    /**
     * Create an instance of {@link AddressBookResponse }
     * 
     */
    public AddressBookResponse createAddressBookResponse() {
        return new AddressBookResponse();
    }

    /**
     * Create an instance of {@link ContactDetailGroup }
     * 
     */
    public ContactDetailGroup createContactDetailGroup() {
        return new ContactDetailGroup();
    }

    /**
     * Create an instance of {@link AddressBookRequest }
     * 
     */
    public AddressBookRequest createAddressBookRequest() {
        return new AddressBookRequest();
    }

    /**
     * Create an instance of {@link ContactCriteriaGroup }
     * 
     */
    public ContactCriteriaGroup createContactCriteriaGroup() {
        return new ContactCriteriaGroup();
    }

    /**
     * Create an instance of {@link MultimediaRequest }
     * 
     */
    public MultimediaRequest createMultimediaRequest() {
        return new MultimediaRequest();
    }

    /**
     * Create an instance of {@link LookupCodesResponse }
     * 
     */
    public LookupCodesResponse createLookupCodesResponse() {
        return new LookupCodesResponse();
    }

    /**
     * Create an instance of {@link CodeGroupType }
     * 
     */
    public CodeGroupType createCodeGroupType() {
        return new CodeGroupType();
    }

    /**
     * Create an instance of {@link CodeDetailType }
     * 
     */
    public CodeDetailType createCodeDetailType() {
        return new CodeDetailType();
    }

    /**
     * Create an instance of {@link InventoryRequest }
     * 
     */
    public InventoryRequest createInventoryRequest() {
        return new InventoryRequest();
    }

    /**
     * Create an instance of {@link InventoryCriteriaGroup }
     * 
     */
    public InventoryCriteriaGroup createInventoryCriteriaGroup() {
        return new InventoryCriteriaGroup();
    }

    /**
     * Create an instance of {@link InventoryDetailGroup }
     * 
     */
    public InventoryDetailGroup createInventoryDetailGroup() {
        return new InventoryDetailGroup();
    }

    /**
     * Create an instance of {@link MediaApplicationLinkRequest }
     * 
     */
    public MediaApplicationLinkRequest createMediaApplicationLinkRequest() {
        return new MediaApplicationLinkRequest();
    }

    /**
     * Create an instance of {@link InventoryResponse }
     * 
     */
    public InventoryResponse createInventoryResponse() {
        return new InventoryResponse();
    }

    /**
     * Create an instance of {@link AccountingGeneralLedgerRequest }
     * 
     */
    public AccountingGeneralLedgerRequest createAccountingGeneralLedgerRequest() {
        return new AccountingGeneralLedgerRequest();
    }

    /**
     * Create an instance of {@link GlCriteriaGroup }
     * 
     */
    public GlCriteriaGroup createGlCriteriaGroup() {
        return new GlCriteriaGroup();
    }

    /**
     * Create an instance of {@link GlDetailGroup }
     * 
     */
    public GlDetailGroup createGlDetailGroup() {
        return new GlDetailGroup();
    }

    /**
     * Create an instance of {@link ProjectProfileRequest }
     * 
     */
    public ProjectProfileRequest createProjectProfileRequest() {
        return new ProjectProfileRequest();
    }

    /**
     * Create an instance of {@link ProjectCriteriaGroup }
     * 
     */
    public ProjectCriteriaGroup createProjectCriteriaGroup() {
        return new ProjectCriteriaGroup();
    }

    /**
     * Create an instance of {@link ProjectDetailGroup }
     * 
     */
    public ProjectDetailGroup createProjectDetailGroup() {
        return new ProjectDetailGroup();
    }

    /**
     * Create an instance of {@link LookupCodesRequest }
     * 
     */
    public LookupCodesRequest createLookupCodesRequest() {
        return new LookupCodesRequest();
    }

    /**
     * Create an instance of {@link LookupCodeCriteriaType }
     * 
     */
    public LookupCodeCriteriaType createLookupCodeCriteriaType() {
        return new LookupCodeCriteriaType();
    }

    /**
     * Create an instance of {@link RSCommonReply }
     * 
     */
    public RSCommonReply createRSCommonReply() {
        return new RSCommonReply();
    }

    /**
     * Create an instance of {@link AccountingGeneralLedgerResponse }
     * 
     */
    public AccountingGeneralLedgerResponse createAccountingGeneralLedgerResponse() {
        return new AccountingGeneralLedgerResponse();
    }

    /**
     * Create an instance of {@link ProjectProfileResponse }
     * 
     */
    public ProjectProfileResponse createProjectProfileResponse() {
        return new ProjectProfileResponse();
    }

    /**
     * Create an instance of {@link AudioVideoRequest }
     * 
     */
    public AudioVideoRequest createAudioVideoRequest() {
        return new AudioVideoRequest();
    }

    /**
     * Create an instance of {@link AudioVideoCriteria }
     * 
     */
    public AudioVideoCriteria createAudioVideoCriteria() {
        return new AudioVideoCriteria();
    }

    /**
     * Create an instance of {@link AudioVideoDetailGroup }
     * 
     */
    public AudioVideoDetailGroup createAudioVideoDetailGroup() {
        return new AudioVideoDetailGroup();
    }

    /**
     * Create an instance of {@link AudioVideoResponse }
     * 
     */
    public AudioVideoResponse createAudioVideoResponse() {
        return new AudioVideoResponse();
    }

    /**
     * Create an instance of {@link AccountingTransactionRequest }
     * 
     */
    public AccountingTransactionRequest createAccountingTransactionRequest() {
        return new AccountingTransactionRequest();
    }

    /**
     * Create an instance of {@link TransactionCriteriaGroup }
     * 
     */
    public TransactionCriteriaGroup createTransactionCriteriaGroup() {
        return new TransactionCriteriaGroup();
    }

    /**
     * Create an instance of {@link InventoryItemtypeType }
     * 
     */
    public InventoryItemtypeType createInventoryItemtypeType() {
        return new InventoryItemtypeType();
    }

    /**
     * Create an instance of {@link ItemtypeCriteriaType }
     * 
     */
    public ItemtypeCriteriaType createItemtypeCriteriaType() {
        return new ItemtypeCriteriaType();
    }

    /**
     * Create an instance of {@link CommonContactType }
     * 
     */
    public CommonContactType createCommonContactType() {
        return new CommonContactType();
    }

    /**
     * Create an instance of {@link SimpleItemListType }
     * 
     */
    public SimpleItemListType createSimpleItemListType() {
        return new SimpleItemListType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link PurchaseOrderListType }
     * 
     */
    public PurchaseOrderListType createPurchaseOrderListType() {
        return new PurchaseOrderListType();
    }

    /**
     * Create an instance of {@link InventoryItemType }
     * 
     */
    public InventoryItemType createInventoryItemType() {
        return new InventoryItemType();
    }

    /**
     * Create an instance of {@link GlAccountcatgType }
     * 
     */
    public GlAccountcatgType createGlAccountcatgType() {
        return new GlAccountcatgType();
    }

    /**
     * Create an instance of {@link AudioVideoArtistInfo }
     * 
     */
    public AudioVideoArtistInfo createAudioVideoArtistInfo() {
        return new AudioVideoArtistInfo();
    }

    /**
     * Create an instance of {@link CustomerActivityType }
     * 
     */
    public CustomerActivityType createCustomerActivityType() {
        return new CustomerActivityType();
    }

    /**
     * Create an instance of {@link AudioVideoTrackInfo }
     * 
     */
    public AudioVideoTrackInfo createAudioVideoTrackInfo() {
        return new AudioVideoTrackInfo();
    }

    /**
     * Create an instance of {@link LookupCodeType }
     * 
     */
    public LookupCodeType createLookupCodeType() {
        return new LookupCodeType();
    }

    /**
     * Create an instance of {@link GlAccounttypeType }
     * 
     */
    public GlAccounttypeType createGlAccounttypeType() {
        return new GlAccounttypeType();
    }

    /**
     * Create an instance of {@link CreditortypeCriteriaType }
     * 
     */
    public CreditortypeCriteriaType createCreditortypeCriteriaType() {
        return new CreditortypeCriteriaType();
    }

    /**
     * Create an instance of {@link XacttypeType }
     * 
     */
    public XacttypeType createXacttypeType() {
        return new XacttypeType();
    }

    /**
     * Create an instance of {@link XacttypeItemType }
     * 
     */
    public XacttypeItemType createXacttypeItemType() {
        return new XacttypeItemType();
    }

    /**
     * Create an instance of {@link ProjectPeriodsType }
     * 
     */
    public ProjectPeriodsType createProjectPeriodsType() {
        return new ProjectPeriodsType();
    }

    /**
     * Create an instance of {@link SalesOrderType }
     * 
     */
    public SalesOrderType createSalesOrderType() {
        return new SalesOrderType();
    }

    /**
     * Create an instance of {@link ResourceCriteriaType }
     * 
     */
    public ResourceCriteriaType createResourceCriteriaType() {
        return new ResourceCriteriaType();
    }

    /**
     * Create an instance of {@link EmployeeType }
     * 
     */
    public EmployeeType createEmployeeType() {
        return new EmployeeType();
    }

    /**
     * Create an instance of {@link EmployeeProjectType }
     * 
     */
    public EmployeeProjectType createEmployeeProjectType() {
        return new EmployeeProjectType();
    }

    /**
     * Create an instance of {@link MimeType }
     * 
     */
    public MimeType createMimeType() {
        return new MimeType();
    }

    /**
     * Create an instance of {@link CustomerListType }
     * 
     */
    public CustomerListType createCustomerListType() {
        return new CustomerListType();
    }

    /**
     * Create an instance of {@link ResourceAccessType }
     * 
     */
    public ResourceAccessType createResourceAccessType() {
        return new ResourceAccessType();
    }

    /**
     * Create an instance of {@link ItemStatusCriteriaType }
     * 
     */
    public ItemStatusCriteriaType createItemStatusCriteriaType() {
        return new ItemStatusCriteriaType();
    }

    /**
     * Create an instance of {@link ResourceSubtypeCriteriaType }
     * 
     */
    public ResourceSubtypeCriteriaType createResourceSubtypeCriteriaType() {
        return new ResourceSubtypeCriteriaType();
    }

    /**
     * Create an instance of {@link BusinessContactCriteria }
     * 
     */
    public BusinessContactCriteria createBusinessContactCriteria() {
        return new BusinessContactCriteria();
    }

    /**
     * Create an instance of {@link GlSubsidiaryType }
     * 
     */
    public GlSubsidiaryType createGlSubsidiaryType() {
        return new GlSubsidiaryType();
    }

    /**
     * Create an instance of {@link XactCodeGroupCriteriaType }
     * 
     */
    public XactCodeGroupCriteriaType createXactCodeGroupCriteriaType() {
        return new XactCodeGroupCriteriaType();
    }

    /**
     * Create an instance of {@link ProjectTaskType }
     * 
     */
    public ProjectTaskType createProjectTaskType() {
        return new ProjectTaskType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link EmployeeCriteriaType }
     * 
     */
    public EmployeeCriteriaType createEmployeeCriteriaType() {
        return new EmployeeCriteriaType();
    }

    /**
     * Create an instance of {@link SalesInvoiceType }
     * 
     */
    public SalesInvoiceType createSalesInvoiceType() {
        return new SalesInvoiceType();
    }

    /**
     * Create an instance of {@link UserLogoutType }
     * 
     */
    public UserLogoutType createUserLogoutType() {
        return new UserLogoutType();
    }

    /**
     * Create an instance of {@link ResourceExtType }
     * 
     */
    public ResourceExtType createResourceExtType() {
        return new ResourceExtType();
    }

    /**
     * Create an instance of {@link CustomerCriteriaType }
     * 
     */
    public CustomerCriteriaType createCustomerCriteriaType() {
        return new CustomerCriteriaType();
    }

    /**
     * Create an instance of {@link ReportAttachmentType }
     * 
     */
    public ReportAttachmentType createReportAttachmentType() {
        return new ReportAttachmentType();
    }

    /**
     * Create an instance of {@link UserAppRolesCriteriaType }
     * 
     */
    public UserAppRolesCriteriaType createUserAppRolesCriteriaType() {
        return new UserAppRolesCriteriaType();
    }

    /**
     * Create an instance of {@link TimesheetType }
     * 
     */
    public TimesheetType createTimesheetType() {
        return new TimesheetType();
    }

    /**
     * Create an instance of {@link GlCriteriaType }
     * 
     */
    public GlCriteriaType createGlCriteriaType() {
        return new GlCriteriaType();
    }

    /**
     * Create an instance of {@link PurchaseOrderItemType }
     * 
     */
    public PurchaseOrderItemType createPurchaseOrderItemType() {
        return new PurchaseOrderItemType();
    }

    /**
     * Create an instance of {@link PurchaseOrderReturnType }
     * 
     */
    public PurchaseOrderReturnType createPurchaseOrderReturnType() {
        return new PurchaseOrderReturnType();
    }

    /**
     * Create an instance of {@link PurchaseOrderStatusType }
     * 
     */
    public PurchaseOrderStatusType createPurchaseOrderStatusType() {
        return new PurchaseOrderStatusType();
    }

    /**
     * Create an instance of {@link SalesOrderListType }
     * 
     */
    public SalesOrderListType createSalesOrderListType() {
        return new SalesOrderListType();
    }

    /**
     * Create an instance of {@link XactCategoryType }
     * 
     */
    public XactCategoryType createXactCategoryType() {
        return new XactCategoryType();
    }

    /**
     * Create an instance of {@link UserProfileCriteriaType }
     * 
     */
    public UserProfileCriteriaType createUserProfileCriteriaType() {
        return new UserProfileCriteriaType();
    }

    /**
     * Create an instance of {@link CreditorCriteriaType }
     * 
     */
    public CreditorCriteriaType createCreditorCriteriaType() {
        return new CreditorCriteriaType();
    }

    /**
     * Create an instance of {@link XactCodeType }
     * 
     */
    public XactCodeType createXactCodeType() {
        return new XactCodeType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link CreditorType }
     * 
     */
    public CreditorType createCreditorType() {
        return new CreditorType();
    }

    /**
     * Create an instance of {@link RoleType }
     * 
     */
    public RoleType createRoleType() {
        return new RoleType();
    }

    /**
     * Create an instance of {@link XactLineitemListType }
     * 
     */
    public XactLineitemListType createXactLineitemListType() {
        return new XactLineitemListType();
    }

    /**
     * Create an instance of {@link VendorItemType }
     * 
     */
    public VendorItemType createVendorItemType() {
        return new VendorItemType();
    }

    /**
     * Create an instance of {@link CountryCriteriaType }
     * 
     */
    public CountryCriteriaType createCountryCriteriaType() {
        return new CountryCriteriaType();
    }

    /**
     * Create an instance of {@link XactCategoryCriteriaType }
     * 
     */
    public XactCategoryCriteriaType createXactCategoryCriteriaType() {
        return new XactCategoryCriteriaType();
    }

    /**
     * Create an instance of {@link ZipcodeCriteriaType }
     * 
     */
    public ZipcodeCriteriaType createZipcodeCriteriaType() {
        return new ZipcodeCriteriaType();
    }

    /**
     * Create an instance of {@link XactListType }
     * 
     */
    public XactListType createXactListType() {
        return new XactListType();
    }

    /**
     * Create an instance of {@link AppRoleType }
     * 
     */
    public AppRoleType createAppRoleType() {
        return new AppRoleType();
    }

    /**
     * Create an instance of {@link ItemCriteriaType }
     * 
     */
    public ItemCriteriaType createItemCriteriaType() {
        return new ItemCriteriaType();
    }

    /**
     * Create an instance of {@link UserResourceAccessCriteriaType }
     * 
     */
    public UserResourceAccessCriteriaType createUserResourceAccessCriteriaType() {
        return new UserResourceAccessCriteriaType();
    }

    /**
     * Create an instance of {@link XactCustomRelationalCriteriaType }
     * 
     */
    public XactCustomRelationalCriteriaType createXactCustomRelationalCriteriaType() {
        return new XactCustomRelationalCriteriaType();
    }

    /**
     * Create an instance of {@link SalesOrderStatusType }
     * 
     */
    public SalesOrderStatusType createSalesOrderStatusType() {
        return new SalesOrderStatusType();
    }

    /**
     * Create an instance of {@link TaskType }
     * 
     */
    public TaskType createTaskType() {
        return new TaskType();
    }

    /**
     * Create an instance of {@link AudioVideoGenreLookup }
     * 
     */
    public AudioVideoGenreLookup createAudioVideoGenreLookup() {
        return new AudioVideoGenreLookup();
    }

    /**
     * Create an instance of {@link StatesCriteriaType }
     * 
     */
    public StatesCriteriaType createStatesCriteriaType() {
        return new StatesCriteriaType();
    }

    /**
     * Create an instance of {@link CreditorListType }
     * 
     */
    public CreditorListType createCreditorListType() {
        return new CreditorListType();
    }

    /**
     * Create an instance of {@link ClientType }
     * 
     */
    public ClientType createClientType() {
        return new ClientType();
    }

    /**
     * Create an instance of {@link CreditorActivityType }
     * 
     */
    public CreditorActivityType createCreditorActivityType() {
        return new CreditorActivityType();
    }

    /**
     * Create an instance of {@link SimpleItemType }
     * 
     */
    public SimpleItemType createSimpleItemType() {
        return new SimpleItemType();
    }

    /**
     * Create an instance of {@link SalesOrderItemType }
     * 
     */
    public SalesOrderItemType createSalesOrderItemType() {
        return new SalesOrderItemType();
    }

    /**
     * Create an instance of {@link InventoryStatusHistoryType }
     * 
     */
    public InventoryStatusHistoryType createInventoryStatusHistoryType() {
        return new InventoryStatusHistoryType();
    }

    /**
     * Create an instance of {@link SalesOrderStatusHistoryType }
     * 
     */
    public SalesOrderStatusHistoryType createSalesOrderStatusHistoryType() {
        return new SalesOrderStatusHistoryType();
    }

    /**
     * Create an instance of {@link XactItemtypeType }
     * 
     */
    public XactItemtypeType createXactItemtypeType() {
        return new XactItemtypeType();
    }

    /**
     * Create an instance of {@link PersonContactCriteria }
     * 
     */
    public PersonContactCriteria createPersonContactCriteria() {
        return new PersonContactCriteria();
    }

    /**
     * Create an instance of {@link CustomerTransactionListType }
     * 
     */
    public CustomerTransactionListType createCustomerTransactionListType() {
        return new CustomerTransactionListType();
    }

    /**
     * Create an instance of {@link ItemAssociationCriteriaType }
     * 
     */
    public ItemAssociationCriteriaType createItemAssociationCriteriaType() {
        return new ItemAssociationCriteriaType();
    }

    /**
     * Create an instance of {@link PurchaseOrderStatusHistoryType }
     * 
     */
    public PurchaseOrderStatusHistoryType createPurchaseOrderStatusHistoryType() {
        return new PurchaseOrderStatusHistoryType();
    }

    /**
     * Create an instance of {@link SalesOrderCriteria }
     * 
     */
    public SalesOrderCriteria createSalesOrderCriteria() {
        return new SalesOrderCriteria();
    }

    /**
     * Create an instance of {@link XactCodeCriteriaType }
     * 
     */
    public XactCodeCriteriaType createXactCodeCriteriaType() {
        return new XactCodeCriteriaType();
    }

    /**
     * Create an instance of {@link ResourcetypeType }
     * 
     */
    public ResourcetypeType createResourcetypeType() {
        return new ResourcetypeType();
    }

    /**
     * Create an instance of {@link RecordTrackingType }
     * 
     */
    public RecordTrackingType createRecordTrackingType() {
        return new RecordTrackingType();
    }

    /**
     * Create an instance of {@link GlAccountType }
     * 
     */
    public GlAccountType createGlAccountType() {
        return new GlAccountType();
    }

    /**
     * Create an instance of {@link TimesheetCriteriaType }
     * 
     */
    public TimesheetCriteriaType createTimesheetCriteriaType() {
        return new TimesheetCriteriaType();
    }

    /**
     * Create an instance of {@link ProjectType }
     * 
     */
    public ProjectType createProjectType() {
        return new ProjectType();
    }

    /**
     * Create an instance of {@link IpCriteriaType }
     * 
     */
    public IpCriteriaType createIpCriteriaType() {
        return new IpCriteriaType();
    }

    /**
     * Create an instance of {@link ResourceType }
     * 
     */
    public ResourceType createResourceType() {
        return new ResourceType();
    }

    /**
     * Create an instance of {@link XactLineitemType }
     * 
     */
    public XactLineitemType createXactLineitemType() {
        return new XactLineitemType();
    }

    /**
     * Create an instance of {@link AudioVideoMediaTypeLookup }
     * 
     */
    public AudioVideoMediaTypeLookup createAudioVideoMediaTypeLookup() {
        return new AudioVideoMediaTypeLookup();
    }

    /**
     * Create an instance of {@link AudioVideoProjectTypeLookup }
     * 
     */
    public AudioVideoProjectTypeLookup createAudioVideoProjectTypeLookup() {
        return new AudioVideoProjectTypeLookup();
    }

    /**
     * Create an instance of {@link EmployeetypeType }
     * 
     */
    public EmployeetypeType createEmployeetypeType() {
        return new EmployeetypeType();
    }

    /**
     * Create an instance of {@link UserAppLoginCheckType }
     * 
     */
    public UserAppLoginCheckType createUserAppLoginCheckType() {
        return new UserAppLoginCheckType();
    }

    /**
     * Create an instance of {@link XacttypeItemActivityType }
     * 
     */
    public XacttypeItemActivityType createXacttypeItemActivityType() {
        return new XacttypeItemActivityType();
    }

    /**
     * Create an instance of {@link PurchaseOrderItemListType }
     * 
     */
    public PurchaseOrderItemListType createPurchaseOrderItemListType() {
        return new PurchaseOrderItemListType();
    }

    /**
     * Create an instance of {@link CommonContactCriteria }
     * 
     */
    public CommonContactCriteria createCommonContactCriteria() {
        return new CommonContactCriteria();
    }

    /**
     * Create an instance of {@link AudioVideoProjectInfo }
     * 
     */
    public AudioVideoProjectInfo createAudioVideoProjectInfo() {
        return new AudioVideoProjectInfo();
    }

    /**
     * Create an instance of {@link CitytypeType }
     * 
     */
    public CitytypeType createCitytypeType() {
        return new CitytypeType();
    }

    /**
     * Create an instance of {@link CustomerType }
     * 
     */
    public CustomerType createCustomerType() {
        return new CustomerType();
    }

    /**
     * Create an instance of {@link TimesheetStatusHistoryType }
     * 
     */
    public TimesheetStatusHistoryType createTimesheetStatusHistoryType() {
        return new TimesheetStatusHistoryType();
    }

    /**
     * Create an instance of {@link TimesheetStatusType }
     * 
     */
    public TimesheetStatusType createTimesheetStatusType() {
        return new TimesheetStatusType();
    }

    /**
     * Create an instance of {@link ApplicationType }
     * 
     */
    public ApplicationType createApplicationType() {
        return new ApplicationType();
    }

    /**
     * Create an instance of {@link XactBasicCriteriaType }
     * 
     */
    public XactBasicCriteriaType createXactBasicCriteriaType() {
        return new XactBasicCriteriaType();
    }

    /**
     * Create an instance of {@link CommonXactType }
     * 
     */
    public CommonXactType createCommonXactType() {
        return new CommonXactType();
    }

    /**
     * Create an instance of {@link ResourceSubtypeType }
     * 
     */
    public ResourceSubtypeType createResourceSubtypeType() {
        return new ResourceSubtypeType();
    }

    /**
     * Create an instance of {@link CreditorActivityListType }
     * 
     */
    public CreditorActivityListType createCreditorActivityListType() {
        return new CreditorActivityListType();
    }

    /**
     * Create an instance of {@link PurchaseOrderCriteria }
     * 
     */
    public PurchaseOrderCriteria createPurchaseOrderCriteria() {
        return new PurchaseOrderCriteria();
    }

    /**
     * Create an instance of {@link BusinessType }
     * 
     */
    public BusinessType createBusinessType() {
        return new BusinessType();
    }

    /**
     * Create an instance of {@link GlBalancetypeType }
     * 
     */
    public GlBalancetypeType createGlBalancetypeType() {
        return new GlBalancetypeType();
    }

    /**
     * Create an instance of {@link XactCriteriaType }
     * 
     */
    public XactCriteriaType createXactCriteriaType() {
        return new XactCriteriaType();
    }

    /**
     * Create an instance of {@link PurchaseOrderType }
     * 
     */
    public PurchaseOrderType createPurchaseOrderType() {
        return new PurchaseOrderType();
    }

    /**
     * Create an instance of {@link XactCategoryListType }
     * 
     */
    public XactCategoryListType createXactCategoryListType() {
        return new XactCategoryListType();
    }

    /**
     * Create an instance of {@link TimezoneCriteriaType }
     * 
     */
    public TimezoneCriteriaType createTimezoneCriteriaType() {
        return new TimezoneCriteriaType();
    }

    /**
     * Create an instance of {@link VendorItemCriteriaType }
     * 
     */
    public VendorItemCriteriaType createVendorItemCriteriaType() {
        return new VendorItemCriteriaType();
    }

    /**
     * Create an instance of {@link EmployeeTitleType }
     * 
     */
    public EmployeeTitleType createEmployeeTitleType() {
        return new EmployeeTitleType();
    }

    /**
     * Create an instance of {@link InventoryItemStatusType }
     * 
     */
    public InventoryItemStatusType createInventoryItemStatusType() {
        return new InventoryItemStatusType();
    }

    /**
     * Create an instance of {@link CreditortypeType }
     * 
     */
    public CreditortypeType createCreditortypeType() {
        return new CreditortypeType();
    }

    /**
     * Create an instance of {@link ItemStatusHistoryCriteriaType }
     * 
     */
    public ItemStatusHistoryCriteriaType createItemStatusHistoryCriteriaType() {
        return new ItemStatusHistoryCriteriaType();
    }

    /**
     * Create an instance of {@link XactCodeGroupListType }
     * 
     */
    public XactCodeGroupListType createXactCodeGroupListType() {
        return new XactCodeGroupListType();
    }

    /**
     * Create an instance of {@link XactType }
     * 
     */
    public XactType createXactType() {
        return new XactType();
    }

    /**
     * Create an instance of {@link UserAppRolesType }
     * 
     */
    public UserAppRolesType createUserAppRolesType() {
        return new UserAppRolesType();
    }

    /**
     * Create an instance of {@link XactCodeGroupType }
     * 
     */
    public XactCodeGroupType createXactCodeGroupType() {
        return new XactCodeGroupType();
    }

    /**
     * Create an instance of {@link SalesOrderItemListType }
     * 
     */
    public SalesOrderItemListType createSalesOrderItemListType() {
        return new SalesOrderItemListType();
    }

    /**
     * Create an instance of {@link XactCodeListType }
     * 
     */
    public XactCodeListType createXactCodeListType() {
        return new XactCodeListType();
    }

    /**
     * Create an instance of {@link FullGroupType }
     * 
     */
    public FullGroupType createFullGroupType() {
        return new FullGroupType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "orderByAvailable")
    public JAXBElement<Boolean> createOrderByAvailable(Boolean value) {
        return new JAXBElement<Boolean>(_OrderByAvailable_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reason")
    public JAXBElement<String> createReason(String value) {
        return new JAXBElement<String>(_Reason_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beanClassName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createBeanClassName(String value) {
        return new JAXBElement<String>(_BeanClassName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "serializeXml")
    public JAXBElement<Boolean> createSerializeXml(Boolean value) {
        return new JAXBElement<Boolean>(_SerializeXml_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xactSubtypeId")
    public JAXBElement<BigInteger> createXactSubtypeId(BigInteger value) {
        return new JAXBElement<BigInteger>(_XactSubtypeId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "glAccountId")
    public JAXBElement<BigInteger> createGlAccountId(BigInteger value) {
        return new JAXBElement<BigInteger>(_GlAccountId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "businessId")
    public JAXBElement<BigInteger> createBusinessId(BigInteger value) {
        return new JAXBElement<BigInteger>(_BusinessId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "resultsetType")
    public JAXBElement<BigInteger> createResultsetType(BigInteger value) {
        return new JAXBElement<BigInteger>(_ResultsetType_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tenderId")
    public JAXBElement<BigInteger> createTenderId(BigInteger value) {
        return new JAXBElement<BigInteger>(_TenderId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dateCreated")
    public JAXBElement<String> createDateCreated(String value) {
        return new JAXBElement<String>(_DateCreated_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xactDate")
    public JAXBElement<String> createXactDate(String value) {
        return new JAXBElement<String>(_XactDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "balance")
    public JAXBElement<BigDecimal> createBalance(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Balance_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "accountNo")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAccountNo(String value) {
        return new JAXBElement<String>(_AccountNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "customerId")
    public JAXBElement<BigInteger> createCustomerId(BigInteger value) {
        return new JAXBElement<BigInteger>(_CustomerId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xactTypeId")
    public JAXBElement<BigInteger> createXactTypeId(BigInteger value) {
        return new JAXBElement<BigInteger>(_XactTypeId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "creditLimit")
    public JAXBElement<BigDecimal> createCreditLimit(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_CreditLimit_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dataSourceClassName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDataSourceClassName(String value) {
        return new JAXBElement<String>(_DataSourceClassName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addrId")
    public JAXBElement<BigInteger> createAddrId(BigInteger value) {
        return new JAXBElement<BigInteger>(_AddrId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "servType")
    public JAXBElement<BigInteger> createServType(BigInteger value) {
        return new JAXBElement<BigInteger>(_ServType_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "busType")
    public JAXBElement<BigInteger> createBusType(BigInteger value) {
        return new JAXBElement<BigInteger>(_BusType_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dataSourcePackage")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDataSourcePackage(String value) {
        return new JAXBElement<String>(_DataSourcePackage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xactId")
    public JAXBElement<BigInteger> createXactId(BigInteger value) {
        return new JAXBElement<BigInteger>(_XactId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "soId")
    public JAXBElement<BigInteger> createSoId(BigInteger value) {
        return new JAXBElement<BigInteger>(_SoId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "inClauseAvailable")
    public JAXBElement<Boolean> createInClauseAvailable(Boolean value) {
        return new JAXBElement<Boolean>(_InClauseAvailable_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "invoiced")
    public JAXBElement<BigInteger> createInvoiced(BigInteger value) {
        return new JAXBElement<BigInteger>(_Invoiced_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "customCriteriaAvailable")
    public JAXBElement<Boolean> createCustomCriteriaAvailable(Boolean value) {
        return new JAXBElement<Boolean>(_CustomCriteriaAvailable_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dataSourceRoot")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDataSourceRoot(String value) {
        return new JAXBElement<String>(_DataSourceRoot_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addrZip")
    public JAXBElement<BigInteger> createAddrZip(BigInteger value) {
        return new JAXBElement<BigInteger>(_AddrZip_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "active")
    public JAXBElement<BigInteger> createActive(BigInteger value) {
        return new JAXBElement<BigInteger>(_Active_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addrZipext")
    public JAXBElement<BigInteger> createAddrZipext(BigInteger value) {
        return new JAXBElement<BigInteger>(_AddrZipext_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userId")
    public JAXBElement<String> createUserId(String value) {
        return new JAXBElement<String>(_UserId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dataSourceName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDataSourceName(String value) {
        return new JAXBElement<String>(_DataSourceName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "orderTotal")
    public JAXBElement<BigDecimal> createOrderTotal(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_OrderTotal_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "criteriaAvailable")
    public JAXBElement<Boolean> createCriteriaAvailable(Boolean value) {
        return new JAXBElement<Boolean>(_CriteriaAvailable_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dateUpdated")
    public JAXBElement<String> createDateUpdated(String value) {
        return new JAXBElement<String>(_DateUpdated_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addrPersonId")
    public JAXBElement<BigInteger> createAddrPersonId(BigInteger value) {
        return new JAXBElement<BigInteger>(_AddrPersonId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xactAmount")
    public JAXBElement<BigDecimal> createXactAmount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_XactAmount_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addrBusinessId")
    public JAXBElement<BigInteger> createAddrBusinessId(BigInteger value) {
        return new JAXBElement<BigInteger>(_AddrBusinessId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "documentId")
    public JAXBElement<BigInteger> createDocumentId(BigInteger value) {
        return new JAXBElement<BigInteger>(_DocumentId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "effectiveDate")
    public JAXBElement<String> createEffectiveDate(String value) {
        return new JAXBElement<String>(_EffectiveDate_QNAME, String.class, null, value);
    }

}
