<?xml version="1.0"?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:include schemaLocation="../schemas/RQ_Us_States_Search.xsd"/>
		</xsd:schema>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:include schemaLocation="../schemas/RS_Us_States_Search.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="InMessage">
		<wsdl:part name="InMessageRequest" element="RQ_us_states_search"/>
	</wsdl:message>
	<wsdl:message name="OutMessage">
		<wsdl:part name="OutMessageResponse" element="RS_us_states_search"/>
	</wsdl:message>
	<wsdl:portType name="UsStatesSearchInterface">
		<wsdl:operation name="Execute">
			<wsdl:input message="InMessage"/>
			<wsdl:output message="OutMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="UsStatesSearchSoapHttpBinding" type="UsStatesSearchInterface">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
		<wsdl:operation name="Execute">
			<soap:operation style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="UsStatesSearchService">
		<wsdl:port name="UsStatesSearchEndpoint" binding="UsStatesSearchSoapHttpBinding">
			<soap:address location="http://www.rmt2.net/ServiceDispatch/soapRouter"/>
<!--
			<soap:address location"http://rmt2.net/ServiceDispatch/soapRouter"/>
-->
		</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>